import "./globals.css";
import Head from "next/head";
import { Hanken_Grotesk } from "next/font/google";

const HankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
});

export const metadata = {
  title: "Summary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <html lang="pt-br">
        <body className={HankenGrotesk.className}>{children}</body>
      </html>
    </>
  );
}
